server:
  port: 8080
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

  datasource:
    second-datasource:
      jdbcUrl: jdbc:clickhouse://clickhouse.clickhouse:8123/test
      username: admin
      password: password
      driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
      connectionTimeout: 100000


  data:
    mongodb:
        host: mongo-db.default
        port: 27017
        database: npm
        password: mongoadmin
        username: mongoadmin
        authentication-database: admin

      #      下面注解，直接使用uri会报错，导致认证失败
      #      uri: mongodb://mongoadmin:mongoadmin@172.29.4.74:30004/test



